### PR TITLE
Disabled fields for web classes.

### PR DESCRIPTION
**Pull request by PatrykSzwer**
For https://github.com/StarcounterApps/Website/issues/116

### CODE REVIEW

**Comment by un-tone** [comment]
Looks good. But you should re-target PR to `develop` branch (see https://github.com/StarcounterApps/Simplified#starcounter-versions-22-and-23 and https://github.com/StarcounterApps/Simplified/issues/63)

**Comment by un-tone** [comment]
We have a small issue here. `develop` branch was not up to date with `master` and that is not correct. I'd just remind about the changes in branches (look at the links in the comment above) and ask @Joltrix to follow the PR way of making code changes in future.

**Comment by Joltrix** [comment]
Ah, I apologize! I will make PRs to Simplified from now on! :)

**Comment by warpech** [comment]
Right now the branches `master` and `develop` are diverged. This should never happen.

@Joltrix can you pls fix this by merging `master -> develop`, then `develop -> master`, then `master -> master-v2.4`).

**Comment by Joltrix** [comment]
Something seems to have happened to the Simplified project, I can't merge / publish or sync.

image

Should I just revert my changes and add them to develop instead and make a PR?

**Pull request merged**
