### PR TITLE
Update readme for installing Simplified in version 2.4

### PR DESCRIPTION
**Pull request by habib535**
Update readme for installing Simplified in version 2.4

### CODE REVIEW

**Comment by habib535** [comment]
Closing as Master is not supposed to be compatible with v2.4

**Comment by habib535** [comment]
Was trying to close a different pull request.

**Comment by Mihaiii** [comment]
Targeting branch was changed to `develop` (which was just restored).

**Comment by PatrykSzwer** [comment]
I think that targeted branch should be the default one (`master` right now), since when You enter repository, readme from default branch is shown.

**Comment by warpech** [comment]
Ping @habib535

**Comment by habib535** [comment]
Text is updated. We will merge this into `develop` then `develop` into `master` and `master` into `master 2.4`  so all the readme will have the updated content.

**Pull request merged**
